name: LbDaire
version: '2.1'
main: org.byauth.ByCircleGame
api-version: '1.18'
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  daire:
    description: Oyuncular için LbDaire komutları.
    usage: /<command>
    aliases: [cg, lbdaire, circlegame]
  daireadmin:
    description: Yöneticiler için LbDaire komutları.
    usage: /<command> <args>
    permission: bycirclegame.admin
    aliases: [cga, lbdaireadmin, circlegameadmin]
  destekle:
    description: İzleyiciyken takım arkadaşlarına yardım etmeni sağlar.
    usage: /destekle
    aliases: [destek]
  kozmetik:
    description: Kazanma efektleri menüsünü açar.
    usage: /kozmetik
    aliases: [cosmetic]

libraries:
  - org.xerial:sqlite-jdbc:3.41.2.2
  - com.google.code.gson:gson:2.10.1